apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: cloudwatch-exporter
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: cloudwatch-exporter
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: sysdig-agent
    ports:
    - port: 9106
      protocol: TCP
